/*
 * DIO_PbCfg.c
 *
 * Created: 7/7/2021 5:40:53 PM
 *  Author: Mohamed Wagdy
 */ 

/*- INCLUDES
----------------------------------------------*/
#include "DIO_PbCfg.h"

/* struct containing all DIO pins configurations. */
const STR_DIO_config_t gastr_DIO_configurations[PINS_NUMBERS] = {
   {PIN_0, PORTA, OUTPUT, DEFAULT_RESISTOR, INITIAL_LOW},
   {PIN_1, PORTA, DEFAULT_DIR, DEFAULT_RESISTOR, DEFAULT_INITIAL},
   {PIN_2, PORTA, DEFAULT_DIR, DEFAULT_RESISTOR, DEFAULT_INITIAL},
   {PIN_3, PORTA, DEFAULT_DIR, DEFAULT_RESISTOR, DEFAULT_INITIAL},
   {PIN_4, PORTA, DEFAULT_DIR, DEFAULT_RESISTOR, DEFAULT_INITIAL},
   {PIN_5, PORTA, DEFAULT_DIR, DEFAULT_RESISTOR, DEFAULT_INITIAL},
   {PIN_6, PORTA, DEFAULT_DIR, DEFAULT_RESISTOR, DEFAULT_INITIAL},
   {PIN_7, PORTA, DEFAULT_DIR, DEFAULT_RESISTOR, DEFAULT_INITIAL},

   {PIN_0, PORTB, DEFAULT_DIR, DEFAULT_RESISTOR, DEFAULT_INITIAL},
   {PIN_1, PORTB, DEFAULT_DIR, DEFAULT_RESISTOR, DEFAULT_INITIAL},
   {PIN_2, PORTB, DEFAULT_DIR, DEFAULT_RESISTOR, DEFAULT_INITIAL},
   {PIN_3, PORTB, DEFAULT_DIR, DEFAULT_RESISTOR, DEFAULT_INITIAL},
   {PIN_4, PORTB, DEFAULT_DIR, DEFAULT_RESISTOR, DEFAULT_INITIAL},
   {PIN_5, PORTB, DEFAULT_DIR, DEFAULT_RESISTOR, DEFAULT_INITIAL},
   {PIN_6, PORTB, DEFAULT_DIR, DEFAULT_RESISTOR, DEFAULT_INITIAL},
   {PIN_7, PORTB, DEFAULT_DIR, DEFAULT_RESISTOR, DEFAULT_INITIAL},

   {PIN_0, PORTC, INPUT, OPEN_DRAIN, DEFAULT_INITIAL},
   {PIN_1, PORTC, DEFAULT_DIR, DEFAULT_RESISTOR, DEFAULT_INITIAL},
   {PIN_2, PORTC, DEFAULT_DIR, DEFAULT_RESISTOR, DEFAULT_INITIAL},
   {PIN_3, PORTC, DEFAULT_DIR, DEFAULT_RESISTOR, DEFAULT_INITIAL},
   {PIN_4, PORTC, DEFAULT_DIR, DEFAULT_RESISTOR, DEFAULT_INITIAL},
   {PIN_5, PORTC, DEFAULT_DIR, DEFAULT_RESISTOR, DEFAULT_INITIAL},
   {PIN_6, PORTC, DEFAULT_DIR, DEFAULT_RESISTOR, DEFAULT_INITIAL},
   {PIN_7, PORTC, DEFAULT_DIR, DEFAULT_RESISTOR, DEFAULT_INITIAL},

   {PIN_0, PORTD, DEFAULT_DIR, DEFAULT_RESISTOR, DEFAULT_INITIAL},
   {PIN_1, PORTD, DEFAULT_DIR, DEFAULT_RESISTOR, DEFAULT_INITIAL},
   {PIN_2, PORTD, DEFAULT_DIR, DEFAULT_RESISTOR, DEFAULT_INITIAL},
   {PIN_3, PORTD, DEFAULT_DIR, DEFAULT_RESISTOR, DEFAULT_INITIAL},
   {PIN_4, PORTD, DEFAULT_DIR, DEFAULT_RESISTOR, DEFAULT_INITIAL},
   {PIN_5, PORTD, DEFAULT_DIR, DEFAULT_RESISTOR, DEFAULT_INITIAL},
   {PIN_6, PORTD, DEFAULT_DIR, DEFAULT_RESISTOR, DEFAULT_INITIAL},
   {PIN_7, PORTD, DEFAULT_DIR, DEFAULT_RESISTOR, DEFAULT_INITIAL},
};
