/*
 * DIO_PbCfg.c
 *
 * Created: 7/7/2021 5:40:53 PM
 *  Author: Mohamed Wagdy
 */ 

/*- INCLUDES
----------------------------------------------*/
#include "DIO_PbCfg.h"

const STR_DIO_config_t gastr_DIO_configurations[PINS_NUMBERS] = {
   {PORTA, PIN_0, OUTPUT, DEFAULT_RESISTOR, INITIAL_LOW},
   {PORTA, PIN_1, DEFAULT_DIR, DEFAULT_RESISTOR, DEFAULT_INITIAL},
   {PORTA, PIN_2, DEFAULT_DIR, DEFAULT_RESISTOR, DEFAULT_INITIAL},
   {PORTA, PIN_3, DEFAULT_DIR, DEFAULT_RESISTOR, DEFAULT_INITIAL},
   {PORTA, PIN_4, DEFAULT_DIR, DEFAULT_RESISTOR, DEFAULT_INITIAL},
   {PORTA, PIN_5, DEFAULT_DIR, DEFAULT_RESISTOR, DEFAULT_INITIAL},
   {PORTA, PIN_6, DEFAULT_DIR, DEFAULT_RESISTOR, DEFAULT_INITIAL},
   {PORTA, PIN_7, DEFAULT_DIR, DEFAULT_RESISTOR, DEFAULT_INITIAL},

   {PORTB, PIN_0, DEFAULT_DIR, DEFAULT_RESISTOR, DEFAULT_INITIAL},
   {PORTB, PIN_1, DEFAULT_DIR, DEFAULT_RESISTOR, DEFAULT_INITIAL},
   {PORTB, PIN_2, DEFAULT_DIR, DEFAULT_RESISTOR, DEFAULT_INITIAL},
   {PORTB, PIN_3, DEFAULT_DIR, DEFAULT_RESISTOR, DEFAULT_INITIAL},
   {PORTB, PIN_4, DEFAULT_DIR, DEFAULT_RESISTOR, DEFAULT_INITIAL},
   {PORTB, PIN_5, DEFAULT_DIR, DEFAULT_RESISTOR, DEFAULT_INITIAL},
   {PORTB, PIN_6, DEFAULT_DIR, DEFAULT_RESISTOR, DEFAULT_INITIAL},
   {PORTB, PIN_7, DEFAULT_DIR, DEFAULT_RESISTOR, DEFAULT_INITIAL},

   {PORTC, PIN_0, INPUT, OPEN_DRAIN, DEFAULT_INITIAL},
   {PORTC, PIN_1, DEFAULT_DIR, DEFAULT_RESISTOR, DEFAULT_INITIAL},
   {PORTC, PIN_2, DEFAULT_DIR, DEFAULT_RESISTOR, DEFAULT_INITIAL},
   {PORTC, PIN_3, DEFAULT_DIR, DEFAULT_RESISTOR, DEFAULT_INITIAL},
   {PORTC, PIN_4, DEFAULT_DIR, DEFAULT_RESISTOR, DEFAULT_INITIAL},
   {PORTC, PIN_5, DEFAULT_DIR, DEFAULT_RESISTOR, DEFAULT_INITIAL},
   {PORTC, PIN_6, DEFAULT_DIR, DEFAULT_RESISTOR, DEFAULT_INITIAL},
   {PORTC, PIN_7, DEFAULT_DIR, DEFAULT_RESISTOR, DEFAULT_INITIAL},

   {PORTD, PIN_0, DEFAULT_DIR, DEFAULT_RESISTOR, DEFAULT_INITIAL},
   {PORTD, PIN_1, DEFAULT_DIR, DEFAULT_RESISTOR, DEFAULT_INITIAL},
   {PORTD, PIN_2, DEFAULT_DIR, DEFAULT_RESISTOR, DEFAULT_INITIAL},
   {PORTD, PIN_3, DEFAULT_DIR, DEFAULT_RESISTOR, DEFAULT_INITIAL},
   {PORTD, PIN_4, DEFAULT_DIR, DEFAULT_RESISTOR, DEFAULT_INITIAL},
   {PORTD, PIN_5, DEFAULT_DIR, DEFAULT_RESISTOR, DEFAULT_INITIAL},
   {PORTD, PIN_6, DEFAULT_DIR, DEFAULT_RESISTOR, DEFAULT_INITIAL},
   {PORTD, PIN_7, DEFAULT_DIR, DEFAULT_RESISTOR, DEFAULT_INITIAL},
};
