/**********************************************************************************************************************
 *  FILE DESCRIPTION
 *  -------------------------------------------------------------------------------------------------------------------
 *         File:  ADC_Lcfg.c
 *       Module:  ADC
 *
 *  Description:  source file for ADC module linking configurations.
 *
 *********************************************************************************************************************/
/*- INCLUDES
----------------------------------------------*/
#include "ADC_Lcfg.h"

const Adc_ConfigType STR_ADCConfig[ADC_CONFIGURED_CHS] = {
  {ADC_CH0, ADC_GROUP3, ADC_GROUP_PRI0, ADC_TRIGG_SRC_SW, ADC_CONV_MODE_ONESHOT, NULL_PTR, ADC_STREAM_BUFFER_LINEAR, 1000},
  {ADC_CH1, ADC_GROUP0, ADC_GROUP_PRI3, ADC_TRIGG_SRC_SW, ADC_CONV_MODE_ONESHOT, NULL_PTR, ADC_STREAM_BUFFER_LINEAR, 0},
  {ADC_CH2, ADC_GROUP0, ADC_GROUP_PRI3, ADC_TRIGG_SRC_SW, ADC_CONV_MODE_ONESHOT, NULL_PTR, ADC_STREAM_BUFFER_LINEAR, 0},
  {ADC_CH3, ADC_GROUP0, ADC_GROUP_PRI3, ADC_TRIGG_SRC_SW, ADC_CONV_MODE_ONESHOT, NULL_PTR, ADC_STREAM_BUFFER_LINEAR, 0},
  {ADC_CH4, ADC_GROUP0, ADC_GROUP_PRI3, ADC_TRIGG_SRC_SW, ADC_CONV_MODE_ONESHOT, NULL_PTR, ADC_STREAM_BUFFER_LINEAR, 0},
  {ADC_CH5, ADC_GROUP0, ADC_GROUP_PRI3, ADC_TRIGG_SRC_SW, ADC_CONV_MODE_ONESHOT, NULL_PTR, ADC_STREAM_BUFFER_LINEAR, 0},
  {ADC_CH6, ADC_GROUP0, ADC_GROUP_PRI3, ADC_TRIGG_SRC_SW, ADC_CONV_MODE_ONESHOT, NULL_PTR, ADC_STREAM_BUFFER_LINEAR, 0},
  {ADC_CH7, ADC_GROUP0, ADC_GROUP_PRI3, ADC_TRIGG_SRC_SW, ADC_CONV_MODE_ONESHOT, NULL_PTR, ADC_STREAM_BUFFER_LINEAR, 0},
  {ADC_CH8, ADC_GROUP1, ADC_GROUP_PRI3, ADC_TRIGG_SRC_SW, ADC_CONV_MODE_ONESHOT, NULL_PTR, ADC_STREAM_BUFFER_LINEAR, 0},
  {ADC_CH9, ADC_GROUP1, ADC_GROUP_PRI3, ADC_TRIGG_SRC_SW, ADC_CONV_MODE_ONESHOT, NULL_PTR, ADC_STREAM_BUFFER_LINEAR, 0},
  {ADC_CH10, ADC_GROUP1, ADC_GROUP_PRI3, ADC_TRIGG_SRC_SW, ADC_CONV_MODE_ONESHOT, NULL_PTR, ADC_STREAM_BUFFER_LINEAR, 0},
  {ADC_CH11, ADC_GROUP1, ADC_GROUP_PRI3, ADC_TRIGG_SRC_SW, ADC_CONV_MODE_ONESHOT, NULL_PTR, ADC_STREAM_BUFFER_LINEAR, 0},
};
