/**********************************************************************************************************************
 *  FILE DESCRIPTION
 *  -------------------------------------------------------------------------------------------------------------------
 *         File:  PORT_Lcfg.c
 *       Module:  PORT
 *
 *  Description:  source file for PORT module linking configurations.
 *
 *********************************************************************************************************************/
/*- INCLUDES
----------------------------------------------*/
#include "PORT_Lcfg.h"

const Port_ConfigType STR_PortsConfig[PORT_PINS_NUM] = {
    {0, PORT_PIN_HIGH, PORT_PIN_OUTPUT, PORT_PIN_PUR, PORT_PIN_CUR_8MA},
    {0, PORT_PIN_LOW, PORT_PIN_INPUT, PORT_PIN_PUR, PORT_PIN_CUR_8MA},
    {0, PORT_PIN_HIGH, PORT_PIN_OUTPUT, PORT_PIN_PUR, PORT_PIN_CUR_8MA},
    {0, PORT_PIN_LOW, PORT_PIN_INPUT, PORT_PIN_PUR, PORT_PIN_CUR_8MA},
    {0, PORT_PIN_HIGH, PORT_PIN_OUTPUT, PORT_PIN_PUR, PORT_PIN_CUR_8MA},
    {0, PORT_PIN_LOW, PORT_PIN_INPUT, PORT_PIN_PUR, PORT_PIN_CUR_8MA},
    {0, PORT_PIN_HIGH, PORT_PIN_OUTPUT, PORT_PIN_PUR, PORT_PIN_CUR_8MA},
    {0, PORT_PIN_LOW, PORT_PIN_INPUT, PORT_PIN_PUR, PORT_PIN_CUR_8MA},
    {0, PORT_PIN_HIGH, PORT_PIN_OUTPUT, PORT_PIN_PUR, PORT_PIN_CUR_8MA},
    {0, PORT_PIN_LOW, PORT_PIN_INPUT, PORT_PIN_PUR, PORT_PIN_CUR_8MA},
    {0, PORT_PIN_HIGH, PORT_PIN_OUTPUT, PORT_PIN_PUR, PORT_PIN_CUR_8MA},
    {0, PORT_PIN_LOW, PORT_PIN_INPUT, PORT_PIN_PUR, PORT_PIN_CUR_8MA},
    {0, PORT_PIN_HIGH, PORT_PIN_OUTPUT, PORT_PIN_PUR, PORT_PIN_CUR_8MA},
    {0, PORT_PIN_LOW, PORT_PIN_INPUT, PORT_PIN_PUR, PORT_PIN_CUR_8MA},
    {0, PORT_PIN_HIGH, PORT_PIN_OUTPUT, PORT_PIN_PUR, PORT_PIN_CUR_8MA},
    {0, PORT_PIN_LOW, PORT_PIN_INPUT, PORT_PIN_PUR, PORT_PIN_CUR_8MA},
    {0, PORT_PIN_LOW, PORT_PIN_OUTPUT, PORT_PIN_PUR, PORT_PIN_CUR_8MA},
    {0, PORT_PIN_LOW, PORT_PIN_OUTPUT, PORT_PIN_PUR, PORT_PIN_CUR_8MA},
    {0, PORT_PIN_LOW, PORT_PIN_OUTPUT, PORT_PIN_PUR, PORT_PIN_CUR_8MA},
    {0, PORT_PIN_LOW, PORT_PIN_OUTPUT, PORT_PIN_PUR, PORT_PIN_CUR_8MA},
    {0, PORT_PIN_LOW, PORT_PIN_OUTPUT, PORT_PIN_PUR, PORT_PIN_CUR_8MA},
    {0, PORT_PIN_LOW, PORT_PIN_OUTPUT, PORT_PIN_PUR, PORT_PIN_CUR_8MA},
    {0, PORT_PIN_LOW, PORT_PIN_OUTPUT, PORT_PIN_PUR, PORT_PIN_CUR_8MA},
    {0, PORT_PIN_LOW, PORT_PIN_OUTPUT, PORT_PIN_PUR, PORT_PIN_CUR_8MA},
    {0, PORT_PIN_LOW, PORT_PIN_OUTPUT, PORT_PIN_PUR, PORT_PIN_CUR_8MA},
    {0, PORT_PIN_LOW, PORT_PIN_OUTPUT, PORT_PIN_PUR, PORT_PIN_CUR_8MA},
    {0, PORT_PIN_LOW, PORT_PIN_OUTPUT, PORT_PIN_PUR, PORT_PIN_CUR_8MA},
    {0, PORT_PIN_LOW, PORT_PIN_OUTPUT, PORT_PIN_PUR, PORT_PIN_CUR_8MA},
    {0, PORT_PIN_LOW, PORT_PIN_OUTPUT, PORT_PIN_PUR, PORT_PIN_CUR_8MA},
    {0, PORT_PIN_LOW, PORT_PIN_OUTPUT, PORT_PIN_PUR, PORT_PIN_CUR_8MA},
    {0, PORT_PIN_LOW, PORT_PIN_OUTPUT, PORT_PIN_PUR, PORT_PIN_CUR_8MA},
    {0, PORT_PIN_LOW, PORT_PIN_OUTPUT, PORT_PIN_PUR, PORT_PIN_CUR_8MA},
    {0, PORT_PIN_LOW, PORT_PIN_OUTPUT, PORT_PIN_PUR, PORT_PIN_CUR_8MA},
    {0, PORT_PIN_LOW, PORT_PIN_OUTPUT, PORT_PIN_PUR, PORT_PIN_CUR_8MA},
    {0, PORT_PIN_LOW, PORT_PIN_OUTPUT, PORT_PIN_PUR, PORT_PIN_CUR_8MA},
    {0, PORT_PIN_LOW, PORT_PIN_OUTPUT, PORT_PIN_PUR, PORT_PIN_CUR_8MA},
    {0, PORT_PIN_LOW, PORT_PIN_OUTPUT, PORT_PIN_PUR, PORT_PIN_CUR_8MA},
    {0, PORT_PIN_LOW, PORT_PIN_OUTPUT, PORT_PIN_PUR, PORT_PIN_CUR_8MA},
    {0, PORT_PIN_LOW, PORT_PIN_INPUT, PORT_PIN_PUR, PORT_PIN_CUR_8MA},
    {0, PORT_PIN_HIGH, PORT_PIN_OUTPUT, PORT_PIN_PUR, PORT_PIN_CUR_8MA},
    {0, PORT_PIN_HIGH, PORT_PIN_OUTPUT, PORT_PIN_PUR, PORT_PIN_CUR_8MA},
    {0, PORT_PIN_HIGH, PORT_PIN_OUTPUT, PORT_PIN_PUR, PORT_PIN_CUR_8MA},
    {0, PORT_PIN_LOW, PORT_PIN_INPUT, PORT_PIN_PUR, PORT_PIN_CUR_8MA},
};
