#include "BLUETOOTH_Mng_Lcfg.h"



const STR_BLUETOOTH_Mng_config_t gastr_BLUETOOTH_Mng_Config[BLUETOOTH_NUMBERS]=
{
	{{BLUETOOTH_UART_PARAM_38400,BAUDRATE_38400},(ptr_uint8_t)BLUETOOTH_ROLE_PARAM_MSTR,BLUETOOTH_NAME,BLUETOOTH_PASSWORD}																					
};